name: build and push docker image
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
jobs:
  dockerhub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: check out parent
      uses: actions/checkout@v4
      with:
        repository: t2-project/microservices
        path: '.'
    - name: check out common
      uses: actions/checkout@v4
      with:
        repository: t2-project/common
        path: './common'
    - name: check out cart
      uses: actions/checkout@v4
      with:
        path: './cart'
    - name: set up jdk
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
    - name: Maven build common
      run: cd common && ./mvnw clean install
    - name: Maven build cart
      run: cd cart && ./mvnw clean install
    - run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Docker build and push (manual)
      run: |
        echo ${{ env.RELEASE_VERSION }}
        cd ./cart
        docker build -t t2project/cart:${{ env.RELEASE_VERSION }} .
        docker push t2project/cart:${{ env.RELEASE_VERSION }}
