name: build, update parent repository and push docker image
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
jobs:
  dockerhub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: check out parent
      uses: actions/checkout@v4
      with:
        repository: t2-project/microservices
        submodules: true
    - name: Pull & update submodules recursively
      run: |
        git submodule update --init --recursive
        git submodule update --recursive --remote
    - name: Commit to parent repository
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions - update submodules"
        git add --all
        git commit -m "Update submodules" || echo "No changes to commit"
        git push
    - name: Set up jdk
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
    - name: Maven build cart
      run: chmod +x mvnw && ./mvnw --projects cart --also-make clean install
    - run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Docker build and push (manual)
      run: |
        echo ${{ env.RELEASE_VERSION }}
        cd ./cart
        docker build -t t2project/cart:${{ env.RELEASE_VERSION }} .
        docker push t2project/cart:${{ env.RELEASE_VERSION }}
